# fly.toml app configuration file generated for donn on 2023-06-02T11:43:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "donn"
primary_region = "hkg"

[env]
  PORT = "8000"

#[processes]
# app = "run --allow-net --allow-env --unstable ./index.ts"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
# processes = ["app"]
